spring:
  application:
    name: hello-spring-cloud-consumer-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 5
      maxQueueSize: 10