spring:
  application:
    name: hello-spring-cloud-consumer-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/